# 📊 Sales Analysis

**Author:** Earanki Sai Rajesh  
**Tools:** Pandas, Matplotlib, Seaborn, Plotly  
**Language:** Python  

---

## Project Overview

This project analyzes a sales dataset using Python to discover meaningful insights through Exploratory Data Analysis (EDA).

### Objectives

- Understand the dataset
- Clean the data
- Analyze sales trends
- Create interactive visualizations
- Generate business insights

In [1]:
#importing the required libraries and dataset
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
df=pd.read_csv(r"C:\Users\esair\Downloads\retail_sales_dataset.csv")
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [2]:
#data exploration
#checking the what columns are present in the dataset and what are the datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [3]:
#checking what are numerical columns and categorical columns
df_numerical=df.select_dtypes(include=['number']).columns.tolist()
df_numerical

['Transaction ID', 'Age', 'Quantity', 'Price per Unit', 'Total Amount']

In [4]:
df_categorical=df.select_dtypes(include=['object','string','category']).columns.tolist()
df_categorical

['Date', 'Customer ID', 'Gender', 'Product Category']

In [5]:
#chaging the data column from object to datetime
df['Date']=pd.to_datetime(df.Date)

In [6]:
#checking if it is changed or not
df.select_dtypes(include=['datetime64']).columns.tolist()

['Date']

In [7]:
#statiscal data
df.describe()

,Transaction ID,Date,Age,Quantity,Price per Unit,Total Amount
count,1000.000000,1000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,2023-07-03 00:25:55.200000256,41.39200,2.514000,179.890000,456.000000
min,1.000000,2023-01-01 00:00:00,18.00000,1.000000,25.000000,25.000000
25%,250.750000,2023-04-08 00:00:00,29.00000,1.000000,30.000000,60.000000
50%,500.500000,2023-06-29 12:00:00,42.00000,3.000000,50.000000,135.000000
75%,750.250000,2023-10-04 00:00:00,53.00000,4.000000,300.000000,900.000000
max,1000.000000,2024-01-01 00:00:00,64.00000,4.000000,500.000000,2000.000000
std,288.819436,NaN,13.68143,1.132734,189.681356,559.997632

In [8]:
#checking if there are any null values
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [9]:
#checking if there are any duplicate values
df.duplicated().sum()

np.int64(0)

Which age group purchases the most Clothing, Electronics, and Beauty products top10?
### Objective

To identify the purchasing patterns of different age groups across product categories of top 10.

In [10]:
df_product_by_age=df.groupby(['Age','Product Category']).size().sort_values(ascending=False).reset_index(name="Count").head(10)
df_product_by_age

   Age Product Category  Count
0   51      Electronics     14
1   43         Clothing     13
2   46           Beauty     13
3   31      Electronics     13
4   64         Clothing     13
5   30           Beauty     12
6   34           Beauty     12
7   50      Electronics     12
8   43      Electronics     12
9   62      Electronics     12

In [11]:
#visualizing the data
fig=px.bar(data_frame=df_product_by_age,x="Age",y="Count",color="Product Category",barmode="group",title="Product Purchases by Age Group",text_auto=True,color_discrete_sequence=px.colors.qualitative.Set2,template="plotly_white")
fig.update_layout(
    width=1400,
    height=600,
    bargap=1,
    title="Top 10 Customer Age-product Category Combinations by Purchase Frequency",
    title_x=0.5
)
fig.update_traces(
    width=1
)
fig.update_xaxes(
    title="Age(Years)",
    dtick=4
)
fig.update_yaxes(
    title="Purchase Count"
)
fig.update_layout(
    title_font=dict(
        family="Arial",
        size=24,
        color="#1F77B4"
    ),
    xaxis_title_font=dict(
        family="Arial",
        size=18,
        color="#2F4F4F"
    ),
    yaxis_title_font=dict(
        family="Arial",
        size=18,
        color="#2F4F4F"
    )
)
fig.show()

📌 Insights
Electronics appears most frequently among the top 10 age–product category combinations, indicating strong purchase activity for this category across multiple age groups.

Customers aged 51 years recorded the highest purchase count (14) for Electronics, making it the most frequent age–category combination in the dataset.

Clothing also shows high demand, with customers aged 43 and 64 each making 13 purchases.

Beauty products reached a maximum purchase count of 13 among customers aged 46, suggesting strong interest in this age group.

Most of the top-performing combinations are concentrated between the ages of 30 and 64, indicating that middle-aged customers contribute significantly to product purchases.

The purchase counts among the top 10 combinations range from 12 to 14, showing relatively consistent demand across these leading age–category combinations.

Which product category contributes the highest share of total units sold?

🎯 Objective
To analyze the distribution of total units sold across different product categories and identify which category contributes the largest share of overall sales. This analysis helps understand customer purchasing preferences and supports inventory planning and product management decisions.

In [12]:
# Group By : Product Category
# Aggregate : Quantity
# Function : Sum
df_Quantity=df.groupby(['Product Category'])['Quantity'].sum().reset_index()
df_Quantity

  Product Category  Quantity
0           Beauty       771
1         Clothing       894
2      Electronics       849

In [13]:
fig=px.pie(data_frame=df_Quantity,names="Product Category",values="Quantity",hole=0.6,hover_name='Product Category',color_discrete_sequence=px.colors.qualitative.Set2,template="plotly_white")
fig.update_traces(
    textinfo="percent+label"
)
fig.update_layout(
    legend=dict(
        y=-0.2,
        x=0.5,
        xanchor="center"
    ),
    title="Distribution of Total Units Sold by Product Category",
     title_font=dict(
            family="Arial",
            size=22,
            color="#1F77B4"
        ),
        title_x=0.5,
        showlegend=False,
        height=600,
        width=1000
)
fig.show()

📌Insights

Clothing contributes the largest share of total units sold (35.6%), making it the highest-selling product category in the dataset.

Electronics accounts for 33.8% of total units sold, closely following Clothing, indicating strong and consistent customer demand.

Beauty represents 30.7% of total units sold, making it the least sold product category, although the difference compared to the other categories is relatively small.

The sales distribution is fairly balanced across all three product categories, with each contributing approximately one-third of the total units sold, suggesting diversified customer purchasing behavior.

The difference between the highest-selling category (Clothing) and the lowest-selling category (Beauty) is only 4.9 percentage points, indicating that customer demand is relatively evenly distributed among all product categories.

Since all three product categories contribute significantly to total sales, maintaining balanced inventory levels across Clothing, Electronics, and Beauty would help meet customer demand and reduce the risk of stock shortages.

How do purchasing patterns differ between male and female customers across different product categories?

🎯 Objective

To analyze how product purchases vary between male and female customers across different product categories. This analysis helps identify customer preferences and supports targeted marketing and inventory planning.

In [14]:
df_purchase=df.groupby(['Gender','Product Category'])['Quantity'].sum().reset_index()
df_purchase

   Gender Product Category  Quantity
0  Female           Beauty       418
1  Female         Clothing       441
2  Female      Electronics       439
3    Male           Beauty       353
4    Male         Clothing       453
5    Male      Electronics       410

In [15]:
fig=px.bar(data_frame=df_purchase,x='Product Category',y="Quantity",barmode="group",color="Gender",    color_discrete_map={
      "Male":"#4C78A8",
    "Female":"#F58518"
})
fig.update_layout(
    title="Product Purchases by Gender Across Product Categories",
    title_font=dict(
            size=22,
            color="#1F77B4",
            family="Arial"
        ),
    showlegend=False,
    width=1000,
    height=600,
    title_x=0.5

)
fig.update_yaxes(
    title="Total Units Purchased"
)
fig.show()

📌 Key Insights

Female customers purchased more Beauty products than male customers, indicating a stronger preference for Beauty products among female shoppers.

Male customers purchased slightly more Clothing products than female customers, making Clothing the most purchased category among male customers.

Female customers recorded higher purchases in Electronics compared to male customers, suggesting strong customer interest in this category.

Clothing and Electronics were the two most purchased product categories, with both genders contributing significantly to their total sales.

The difference in purchase quantity between male and female customers is relatively small across most product categories, indicating balanced purchasing behavior between genders.

The purchasing preferences vary across product categories, highlighting opportunities for businesses to design targeted marketing campaigns and promotional offers for different customer segments.

Does customer age influence clothing purchase quantity?

🎯 Objective

To examine whether there is a relationship between customer age and the quantity of clothing products purchased. This analysis helps determine whether age is a significant factor influencing clothing purchasing behavior.

In [16]:
df_cutomer=df[df['Product Category']=="Clothing"]
df_cutomer

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200
10,11,2023-02-14,CUST011,Male,23,Clothing,2,50,100
...,...,...,...,...,...,...,...,...,...
986,987,2023-04-29,CUST987,Female,30,Clothing,3,300,900
987,988,2023-05-28,CUST988,Female,63,Clothing,3,25,75
990,991,2023-12-26,CUST991,Female,34,Clothing,2,50,100
994,995,2023-04-30,CUST995,Female,41,Clothing,1,30,30
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50

In [17]:
df_cutomer.groupby('Age')['Quantity'].sum().reset_index()

    Age  Quantity
0    18        19
1    19         8
2    20        11
3    21        18
4    22        23
5    23        24
6    24         9
7    25        17
8    26        29
9    27        18
10   28        21
11   29        17
12   30        10
13   31        17
14   32        21
15   33        13
16   34        20
17   35        23
18   36        18
19   37        23
20   38         9
21   39         9
22   40        26
23   41        23
24   42        22
25   43        38
26   44        25
27   45         9
28   46         8
29   47        30
30   48        19
31   49        19
32   50        14
33   51        24
34   52        23
35   53        20
36   54        28
37   55        14
38   56        20
39   57        21
40   58        12
41   59        17
42   60        22
43   61        18
44   62        11
45   63        18
46   64        36

In [18]:
fig=px.scatter(data_frame=df_cutomer,x='Age',y="Quantity",trendline='ols',title="Relationship Between Age and Clothing Purchases")
fig.update_traces(visible=False,selector=dict(mode="markers"))
fig.update_layout(
    
    width=600
)
fig.show()

📌 Key Insights
The regression trendline shows a slight negative relationship between customer age and clothing purchase quantity.

As customer age increases, the average clothing purchase quantity tends to decrease slightly, although the decline is minimal.

The gentle slope of the regression line indicates that age has only a weak influence on clothing purchase quantity.

No strong upward or downward trend is observed, suggesting that customers across different age groups purchase clothing in relatively similar quantities.

Based on this analysis, customer age alone does not appear to be a major factor in determining clothing purchase quantity, and additional factors such as customer preferences, pricing, or promotions may have a greater impact on purchasing behavior.

During which month were the highest sales recorded?

🎯 Objective

To analyze monthly sales performance by identifying the total sales generated in each month. This analysis helps uncover seasonal sales trends, determine the best-performing month, and support better business planning, inventory management, and marketing strategies.

In [ ]:
month_order = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

df_month["Month"] = pd.Categorical(
    df_month["Month"],
    categories=month_order,
    ordered=True
)

df_month = df_month.sort_values("Month")

In [32]:
df_month=df.groupby('Month')['Total Amount'].sum().reset_index()
fig=px.line(data_frame=df_month,x='Month',y="Total Amount")
fig.show()